language: java
dist: trusty
jdk: oraclejdk8
install:
  - mvn clean -Dapi.key=apiKey -Dtest.api.key=testApiKey -B -V
  - mvn install -Dapi.key=apiKey -Dtest.api.key=testApiKey -DskipTests=true -Dmaven.javadoc.skip=true -B -V