language: java
dist: trusty
jdk: oraclejdk8
script:
  - jdk_switcher use oraclejdk8
  - mvn clean install -Dapi.key=api.key -Dtest.api.key=test.api.key -DskipTests=true -Dmaven.javadoc.skip=true -B -V